### ISSUE TITLE
[Feat] 가게 카테고리 생성 기능

### ISSUE THREAD

**Issue by muncool39** [ewoo14/CodeBloom#30]
## Description

가게 카테고리를 생성하는 API를 개발합니다.

## TODO

- [x] 카테고리 생성 요청 객체 추가
- [x] 권한 매니저, 마스터 확인
- [x] 카테고리명 중복 처리
