### ISSUE TITLE
[Feat] 가게 카테고리 수정 기능

### ISSUE THREAD

**Issue by muncool39** [ewoo14/CodeBloom#40]
## Description

가게 카테고리를 수정하는 API를 개발합니다.

## TODO

- [x] 권한 MASTER, MANAGER 인지 확인
- [x] DB 반영 확인
- [x] 수정 요청 객체 추가
